### ISSUE TITLE
Llama 3.1 Load Fail

### ISSUE THREAD

**Issue by DefinitlyEvil** [thunlp/InfLLM#51]
Output: 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File ".../x/InfLLM/inf_llm/chat.py", line 726, in <module>
    main(args)
  File ".../x/InfLLM/inf_llm/chat.py", line 591, in main
    chat_loop(
  File ".../x/InfLLM/inf_llm/chat.py", line 347, in chat_loop
    model = patch_hf(model, inf_llm_config.type,  **inf_llm_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../x/InfLLM/inf_llm/utils/patch.py", line 156, in patch_hf
    hf_rope.dim,
    ^^^^^^^^^^^
  File ".../conda/envs/infllm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LlamaRotaryEmbedding' object has no attribute 'dim'
```

Even with Llama 3: 
```
    model = patch_hf(model, inf_llm_config.type,  **inf_llm_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../InfLLM/inf_llm/utils/patch.py", line 156, in patch_hf
    hf_rope.dim,
    ^^^^^^^^^^^
  File ".../conda/envs/infllm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LlamaRotaryEmbedding' object has no attribute 'dim'
```

**Comment by yuanyehome** [comment]
Hi, I got the same error. Did you fix it?

**Comment by DefinitlyEvil** [comment]
> Hi, I got the same error. Did you fix it?

Yes, the API seemed changed, but it still didn't work well for me.

**Comment by yuanyehome** [comment]
> > Hi, I got the same error. Did you fix it?
> 
> Yes, the API seemed changed, but it still didn't work well for me.

I've changed the code to this:
![image](https://github.com/user-attachments/assets/66ab001f-7897-4feb-955f-cad99f062d0e)

It can run now. But I can't reproduce the baseline results(mistral-origin/llama3-origin) in the paper. It's really strange that I got a much lower score for the origin setting.

**Comment by DefinitlyEvil** [comment]
> > > Hi, I got the same error. Did you fix it?
> > 
> > 
> > Yes, the API seemed changed, but it still didn't work well for me.
> 
> I've changed the code to this: ![image](https://private-user-images.githubusercontent.com/36473484/385162316-66ab001f-7897-4feb-955f-cad99f062d0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MTUxNDIsIm5iZiI6MTczMTQxNDg0MiwicGF0aCI6Ii8zNjQ3MzQ4NC8zODUxNjIzMTYtNjZhYjAwMWYtNzg5Ny00ZmViLTk1NWYtY2FkOTlmMDYyZDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEyMzQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YjZlOGIzMWQ0ZDRjMTYwM2I4MDk2N2VjOTU2ZWQ3OGM5NGQxNjZkYThhYmI4OTNmNjY4ZTFkNTQ3NGQ0MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LmsdjHbovBHArzWJKaaST-goXgr4fpP2jIM80yYoWLU)
> 
> It can run now. But I can't reproduce the baseline results(mistral-origin/llama3-origin) in the paper. It's really strange that I got a much lower score for the origin setting.

Yes the performance is worse as I observed.
